production:
  membership_expiration_reminder:
    class: MembershipExpirationReminderJob
    queue: default
    schedule: every day at 8am

staging:
  membership_expiration_reminder:
    class: MembershipExpirationReminderJob
    queue: default
    schedule: every day at 8am
