name: ci-auto-lint

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ci-auto-lint-${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  autocorrect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.1"
          bundler-cache: true
      - name: Run RuboCop
        run: bin/rubocop --format github --force-exclusion
